# Generated by Django 2.2.6 on 2019-10-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.TextField(max_length=28)),
                ('precios', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsa', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='foto')),
                ('precio', models.IntegerField(default=0)),
                ('capacidad', models.IntegerField(default=0)),
                ('informacion', models.TextField(max_length=200)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concesionaria.Clases')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concesionaria.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1000)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('consulta', models.TextField(max_length=1000)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concesionaria.Clases')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concesionaria.Habitacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concesionaria.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.TextField(max_length=200)),
                ('vigencia', models.TextField()),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concesionaria.Habitacion')),
            ],
        ),
    ]
