# Generated by Django 2.2.6 on 2019-11-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concesionaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='dsa',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
