# Generated by Django 2.2.6 on 2019-11-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Concesionaria', '0003_auto_20191101_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='habitacion',
        ),
    ]
